# Usage
#   Start:          docker compose up
#   With helpers:   docker compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml up
#   Stop:           docker compose down
#   Destroy:        docker compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml down -v --remove-orphans

version: "3.8"

services:
  # db:
  #   image: postgres:16beta2
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: test
  #   volumes:
  #     - ./data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - 3030:3030
    environment:
      DB_DSN: postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

# If you want to use logging, please run with `docker compose -f docker-compose.yml -f docker-compose-logging.yml up`
